cloud:
  aws:
    s3:
      bucket:
        name: spotlive1
        url: https://spotlive1.s3.ap-northeast-2.amazonaws.com/
    credentials:
      accessKey: AKIAQVMLWIPB4E53HO4M
      secretKey: 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

openvidu:
  server:
    url: https://i5a405.p.ssafy.io:8443
    id: OPENVIDUAPP
    secret: MY_SECRET

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 68c5cb3f22fe800fc5606851a8bed982
            client-secret: GDOD65MV18g96VrQ4LtAlmKiA27S223S

  datasource:
    url: jdbc:mysql://i5a405.p.ssafy.io:3306/spotlive?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: ssafy
      password: spotlive1!