cloud:
  aws:
    s3:
      bucket:
        name: spotlive
        url: https://spotlive.s3.ap-northeast-2.amazonaws.com/
    credentials:
      accessKey: AKIAWEWWG6ADJ4UIA7HW
      secretKey: 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

openvidu:
  server:
    url: https://i5a405.p.ssafy.io
    id: OPENVIDUAPP
    secret: MY_SECRET

spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 68c5cb3f22fe800fc5606851a8bed982
            client-secret: GDOD65MV18g96VrQ4LtAlmKiA27S223S

  datasource:
    url: jdbc:mysql://i5a405.p.ssafy.io:3306/spotlive?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Seoul&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true
    hikari:
      username: ssafy
      password: spotlive1!